#!/bin/sh
# db - shortcut for docker build command
# first arg is the image tag
# Registry/user prefix comes from $DOCKER_USER, default stefian22. Set it per
# environment: DOCKER_USER=gcr.io/$GOOGLE_CLOUD_PROJECT in a GCP lab.

echo docker build -t "${DOCKER_USER:-stefian22}/$1" .

docker build -t "${DOCKER_USER:-stefian22}/$1" .