#!/bin/sh
# dp - shortcut for docker push
# first arg is the container name/tag
# Registry/user prefix comes from $DOCKER_USER, default stefian22. Set it per
# environment: DOCKER_USER=gcr.io/$GOOGLE_CLOUD_PROJECT in a GCP lab.

echo docker push "${DOCKER_USER:-stefian22}/$1"

docker push "${DOCKER_USER:-stefian22}/$1"