#!/bin/sh
# hcg - shortcut for hub create github live-ai/repo for Google Cloud project
# first arg is org-name/repo-name
# other optional args -d description, -h url
# hub create -d Description -h example.com org_name/foo_repo

echo hub create live-ai/"$1" -d "$1" web app -h https://"$1".web.app 

hub create live-ai/"$1" -d "$1" web app -h https://"$1".web.app 