#!/bin/sh
# sed-section - cmd to replace Section with ## Section / Udemy courses
# first arg is the initial file, second arg is the new file
# eg: sed 's/Section/## Section/g' UX-design-theory.txt > ux-design.txt

echo sed 's/Section/## Section/g' "$1" > "$2"

sed 's/Section/## Section/g' "$1" > "$2"
