#!/bin/sh
# sed-section - cmd to replace \n(\d+)min\n with ` $1min` / Udemy courses
# first arg is the initial file, second arg is the new file
# eg: sed 's/\n(\d+)min\n/` $1min`/g' UX-design-theory.txt > ux-design.txt

echo sed 's/\n(\d+)min\n/` $1min`/g' "$1" > "$2"

sed 's/\n(\d+)min\n/` $1min`/g' "$1" > "$2"
